name: Run

on:
  workflow_dispatch:
    inputs:
      ipa:
        description: "Direct URL to IPA file"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Set up workspace
        run: |
          mkdir -p ${{ github.workspace }}/deb-package/DEBIAN
          mkdir -p ${{ github.workspace }}/deb-package/Applications

      - name: Download IPA
        run: |
          curl -L -o ${{ github.workspace }}/deb-package/Applications/App.ipa "${{ github.event.inputs.ipa }}"

      - name: Create DEBIAN control file
        run: |
          cat <<EOF > ${{ github.workspace }}/deb-package/DEBIAN/control
          Package: your-app-name
          Version: 1.0.0
          Section: base
          Priority: optional
          Architecture: all
          Maintainer: Your Name <youremail@example.com>
          Description: Description of your app.
          EOF

      - name: (Optional) Add post-install scripts
        run: |
          cat <<EOF > ${{ github.workspace }}/deb-package/DEBIAN/postinst
          #!/bin/bash
          echo "Post-installation script running"
          # Example: Change permissions of the IPA
          chmod 755 /Applications/App.ipa
          EOF
          chmod 755 ${{ github.workspace }}/deb-package/DEBIAN/postinst

      - name: Build DEB Package
        run: |
          dpkg-deb --build ${{ github.workspace }}/deb-package ${{ github.workspace }}/App.deb

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: App.deb
          path: ${{ github.workspace }}/App.deb
